"""initial migration

Revision ID: c838c872f2e0
Revises: 
Create Date: 2026-03-02 15:22:34.083690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c838c872f2e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
